#############################################################################
# Makefile for building: Befreit_den_Kraken
# Generated by qmake (2.01a) (Qt 4.8.7) on: Do. Okt 25 18:58:47 2018
# Project:  Befreit_den_Kraken.pro
# Template: app
# Command: /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake -o Makefile Befreit_den_Kraken.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/../../usr/lib/arm-linux-gnueabihf -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabihf -L/home/pi/Befreit_den_Kraken/../../../../../usr/lib/arm-linux-gnueabihf/ -liw -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mcp3008Spi.cpp \
		wlan_dialog.cpp \
		sensorscanner.cpp \
		calibrate_ph_dialog.cpp \
		uhr.cpp \
		calibrate_trueb_dialog.cpp \
		database.cpp moc_mainwindow.cpp \
		moc_wlan_dialog.cpp \
		moc_sensorscanner.cpp \
		moc_calibrate_ph_dialog.cpp \
		moc_uhr.cpp \
		moc_calibrate_trueb_dialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		mcp3008Spi.o \
		wlan_dialog.o \
		sensorscanner.o \
		calibrate_ph_dialog.o \
		uhr.o \
		calibrate_trueb_dialog.o \
		database.o \
		moc_mainwindow.o \
		moc_wlan_dialog.o \
		moc_sensorscanner.o \
		moc_calibrate_ph_dialog.o \
		moc_uhr.o \
		moc_calibrate_trueb_dialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Befreit_den_Kraken.pro
QMAKE_TARGET  = Befreit_den_Kraken
DESTDIR       = 
TARGET        = Befreit_den_Kraken

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /home/pi/Befreit_den_Kraken/../../../../../usr/lib/arm-linux-gnueabihf/libiw.a ui_mainwindow.h ui_wlan_dialog.h ui_calibrate_ph_dialog.h ui_calibrate_trueb_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Befreit_den_Kraken.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabihf/libQtSql.prl \
		/usr/lib/arm-linux-gnueabihf/libQtGui.prl \
		/usr/lib/arm-linux-gnueabihf/libQtNetwork.prl \
		/usr/lib/arm-linux-gnueabihf/libQtCore.prl
	$(QMAKE) -o Makefile Befreit_den_Kraken.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabihf/libQtSql.prl:
/usr/lib/arm-linux-gnueabihf/libQtGui.prl:
/usr/lib/arm-linux-gnueabihf/libQtNetwork.prl:
/usr/lib/arm-linux-gnueabihf/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Befreit_den_Kraken.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Befreit_den_Kraken1.0.0 || $(MKDIR) .tmp/Befreit_den_Kraken1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Befreit_den_Kraken1.0.0/ && $(COPY_FILE) --parents mainwindow.h mcp3008Spi.h wlan_dialog.h sensorscanner.h calibrate_ph_dialog.h uhr.h calibrate_trueb_dialog.h database.h .tmp/Befreit_den_Kraken1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp mcp3008Spi.cpp wlan_dialog.cpp sensorscanner.cpp calibrate_ph_dialog.cpp uhr.cpp calibrate_trueb_dialog.cpp database.cpp .tmp/Befreit_den_Kraken1.0.0/ && $(COPY_FILE) --parents mainwindow.ui wlan_dialog.ui calibrate_ph_dialog.ui calibrate_trueb_dialog.ui .tmp/Befreit_den_Kraken1.0.0/ && (cd `dirname .tmp/Befreit_den_Kraken1.0.0` && $(TAR) Befreit_den_Kraken1.0.0.tar Befreit_den_Kraken1.0.0 && $(COMPRESS) Befreit_den_Kraken1.0.0.tar) && $(MOVE) `dirname .tmp/Befreit_den_Kraken1.0.0`/Befreit_den_Kraken1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Befreit_den_Kraken1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_wlan_dialog.cpp moc_sensorscanner.cpp moc_calibrate_ph_dialog.cpp moc_uhr.cpp moc_calibrate_trueb_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_wlan_dialog.cpp moc_sensorscanner.cpp moc_calibrate_ph_dialog.cpp moc_uhr.cpp moc_calibrate_trueb_dialog.cpp
moc_mainwindow.cpp: mcp3008Spi.h \
		sensorscanner.h \
		calibrate_ph_dialog.h \
		mainwindow.h \
		uhr.h \
		calibrate_trueb_dialog.h \
		mainwindow.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_wlan_dialog.cpp: ui_wlan_dialog.h \
		wlan_dialog.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) wlan_dialog.h -o moc_wlan_dialog.cpp

moc_sensorscanner.cpp: mcp3008Spi.h \
		sensorscanner.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) sensorscanner.h -o moc_sensorscanner.cpp

moc_calibrate_ph_dialog.cpp: mainwindow.h \
		mcp3008Spi.h \
		sensorscanner.h \
		calibrate_ph_dialog.h \
		uhr.h \
		calibrate_trueb_dialog.h \
		calibrate_ph_dialog.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) calibrate_ph_dialog.h -o moc_calibrate_ph_dialog.cpp

moc_uhr.cpp: uhr.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) uhr.h -o moc_uhr.cpp

moc_calibrate_trueb_dialog.cpp: mainwindow.h \
		mcp3008Spi.h \
		sensorscanner.h \
		calibrate_ph_dialog.h \
		uhr.h \
		calibrate_trueb_dialog.h \
		calibrate_trueb_dialog.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) calibrate_trueb_dialog.h -o moc_calibrate_trueb_dialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_wlan_dialog.h ui_calibrate_ph_dialog.h ui_calibrate_trueb_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_wlan_dialog.h ui_calibrate_ph_dialog.h ui_calibrate_trueb_dialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_wlan_dialog.h: wlan_dialog.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic wlan_dialog.ui -o ui_wlan_dialog.h

ui_calibrate_ph_dialog.h: calibrate_ph_dialog.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic calibrate_ph_dialog.ui -o ui_calibrate_ph_dialog.h

ui_calibrate_trueb_dialog.h: calibrate_trueb_dialog.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic calibrate_trueb_dialog.ui -o ui_calibrate_trueb_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		mcp3008Spi.h \
		sensorscanner.h \
		calibrate_ph_dialog.h \
		uhr.h \
		calibrate_trueb_dialog.h \
		database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mcp3008Spi.h \
		sensorscanner.h \
		calibrate_ph_dialog.h \
		uhr.h \
		calibrate_trueb_dialog.h \
		ui_mainwindow.h \
		wlan_dialog.h \
		ui_wlan_dialog.h \
		database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mcp3008Spi.o: mcp3008Spi.cpp mcp3008Spi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mcp3008Spi.o mcp3008Spi.cpp

wlan_dialog.o: wlan_dialog.cpp wlan_dialog.h \
		ui_wlan_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wlan_dialog.o wlan_dialog.cpp

sensorscanner.o: sensorscanner.cpp sensorscanner.h \
		mcp3008Spi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensorscanner.o sensorscanner.cpp

calibrate_ph_dialog.o: calibrate_ph_dialog.cpp calibrate_ph_dialog.h \
		mainwindow.h \
		mcp3008Spi.h \
		sensorscanner.h \
		uhr.h \
		calibrate_trueb_dialog.h \
		ui_calibrate_ph_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrate_ph_dialog.o calibrate_ph_dialog.cpp

uhr.o: uhr.cpp uhr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uhr.o uhr.cpp

calibrate_trueb_dialog.o: calibrate_trueb_dialog.cpp calibrate_trueb_dialog.h \
		mainwindow.h \
		mcp3008Spi.h \
		sensorscanner.h \
		calibrate_ph_dialog.h \
		uhr.h \
		ui_calibrate_trueb_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrate_trueb_dialog.o calibrate_trueb_dialog.cpp

database.o: database.cpp database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_wlan_dialog.o: moc_wlan_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wlan_dialog.o moc_wlan_dialog.cpp

moc_sensorscanner.o: moc_sensorscanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sensorscanner.o moc_sensorscanner.cpp

moc_calibrate_ph_dialog.o: moc_calibrate_ph_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibrate_ph_dialog.o moc_calibrate_ph_dialog.cpp

moc_uhr.o: moc_uhr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uhr.o moc_uhr.cpp

moc_calibrate_trueb_dialog.o: moc_calibrate_trueb_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibrate_trueb_dialog.o moc_calibrate_trueb_dialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

